### ISSUE TITLE
Asterisks in properties should be between quotes.

### ISSUE THREAD

**Issue by svenpopping** [WISVCH/payments#56]
```
endpoints.cors:
    allow-credentials: *
    allowed-origins: *
    allowed-methods: *
    allowed-headers: *
```

The asterisks should be between quotes.
